<?php
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
require_once $GLOBALS['THRIFT_ROOT'].'/Thrift.php';

//require_once $GLOBALS['THRIFT_ROOT'].'/packages/scribe/scribe_types.php';



///had to hack interface and remove dupe class here!!

interface ScribeIf {}

class ScribeClient implements ScribeIf, IThriftClient {
  protected $input_ = null;
  protected $output_ = null;

  protected $seqid_ = 0;

  public function __construct(TProtocol $input, /*?TProtocol*/ $output=null) {
    $this->input_ = $input;
    $this->output_ = $output ? $output : $input;
    $this->eventHandler_ = new TClientEventHandler();
  }

  public function setEventHandler(TClientEventHandler $event_handler) {
    $this->eventHandler_ = $event_handler;
  }

  public function getEventHandler() {
    return $this->eventHandler_;
  }

  private function getsequenceid() {
    $currentseqid = $this->seqid_;
    if ($this->seqid_ >= 0x7fffffff) {
       $this->seqid_ = 0;
    } else {
       $this->seqid_++;
    }
    return $currentseqid;
  }

  /**
   * Original thrift definition:-
   * ResultCode
   *   Log(1: list<LogEntry> messages);
   */
  public function Log($messages)
  {
    $currentseqid = $this->send_Log($messages);
    return $this->recv_Log($currentseqid);
  }

  public function send_Log($messages)
  {
    $currentseqid = $this->getsequenceid();
    $args = new Scribe_Log_args();
    $args->messages = $messages;
    try {
      $this->eventHandler_->preSend('Log', $args, $currentseqid);
      $bin_accel = ($this->output_ instanceof TProtocol::$TBINARYPROTOCOLACCELERATED) && function_exists('thrift_protocol_write_binary');
      $compact_accel = ($this->output_ instanceof TProtocol::$TCOMPACTPROTOCOLACCELERATED) && function_exists('thrift_protocol_write_compact') && TCompactProtocolAccelerated::checkVersion(1);
      if ($bin_accel)
      {
        thrift_protocol_write_binary($this->output_, 'Log', TMessageType::CALL, $args, $currentseqid, $this->output_->isStrictWrite(), false);
      }
      else if ($compact_accel)
      {
        thrift_protocol_write_compact($this->output_, 'Log', TMessageType::CALL, $args, $currentseqid, false);
      }
      else
      {
        $this->output_->writeMessageBegin('Log', TMessageType::CALL, $currentseqid);
        $args->write($this->output_);
        $this->output_->writeMessageEnd();
        $this->output_->getTransport()->flush();
      }
    } catch (THandlerShortCircuitException $ex) {
      switch ($ex->resultType) {
        case THandlerShortCircuitException::R_EXPECTED_EX:
        case THandlerShortCircuitException::R_UNEXPECTED_EX:
          $this->eventHandler_->sendError('Log', $args, $currentseqid, $ex->result);
          throw $ex->result;
        case THandlerShortCircuitException::R_SUCCESS:
        default:
          $this->eventHandler_->postSend('Log', $args, $currentseqid);
          return $currentseqid;
      }
    } catch (Exception $ex) {
      $this->eventHandler_->sendError('Log', $args, $currentseqid, $ex);
      throw $ex;
    }
    $this->eventHandler_->postSend('Log', $args, $currentseqid);
    return $currentseqid;
  }

  public function recv_Log($expectedsequenceid = null)
  {
    try {
      $this->eventHandler_->preRecv('Log', $expectedsequenceid);
      $bin_accel = ($this->input_ instanceof TProtocol::$TBINARYPROTOCOLACCELERATED) && function_exists('thrift_protocol_read_binary');
      $compact_accel = ($this->input_ instanceof TProtocol::$TCOMPACTPROTOCOLACCELERATED) && function_exists('thrift_protocol_read_compact') && TCompactProtocolAccelerated::checkVersion(1);
      if ($bin_accel) $result = thrift_protocol_read_binary($this->input_, 'Scribe_Log_result', $this->input_->isStrictRead());
      else if ($compact_accel) $result = thrift_protocol_read_compact($this->input_, 'Scribe_Log_result');
      else
      {
        $rseqid = 0;
        $fname = null;
        $mtype = 0;

        $this->input_->readMessageBegin($fname, $mtype, $rseqid);
        if ($mtype == TMessageType::EXCEPTION) {
          $x = new TApplicationException();
          $x->read($this->input_);
          $this->input_->readMessageEnd();
          throw $x;
        }
        $result = new Scribe_Log_result();
        $result->read($this->input_);
        $this->input_->readMessageEnd();
        if (isset($expectedsequenceid) && ($rseqid != $expectedsequenceid)) {
          throw new TProtocolException("Log failed: sequence id is out of order");
        }
      }
    } catch (THandlerShortCircuitException $ex) {
      switch ($ex->resultType) {
        case THandlerShortCircuitException::R_EXPECTED_EX:
          $this->eventHandler_->recvException('Log', $expectedsequenceid, $ex->result);
          throw $ex->result;
        case THandlerShortCircuitException::R_UNEXPECTED_EX:
          $this->eventHandler_->recvError('Log', $expectedsequenceid, $ex->result);
          throw $ex->result;
        case THandlerShortCircuitException::R_SUCCESS:
        default:
          $this->eventHandler_->postRecv('Log', $expectedsequenceid, $ex->result);
          return $ex->result;
      }
    } catch (Exception $ex) {
      $this->eventHandler_->recvError('Log', $expectedsequenceid, $ex);
      throw $ex;
    }
    if ($result->success !== null) {
      $this->eventHandler_->postRecv('Log', $expectedsequenceid, $result->success);
      return $result->success;
    }
    $x = new TApplicationException("Log failed: unknown result", TApplicationException::MISSING_RESULT);
    $this->eventHandler_->recvError('Log', $expectedsequenceid, $x);
    throw $x;
  }

}


class ScribeProcessor implements IThriftProcessor {
  protected $handler_ = null;
  protected $eventHandler_ = null;
  public function __construct(ScribeIf $handler) {
    $this->handler_ = $handler;
    $this->eventHandler_ = new TProcessorEventHandler();
  }

  public function setEventHandler(TProcessorEventHandler $event_handler) {
    $this->eventHandler_ = $event_handler;
  }

  public function getEventHandler() {
    return $this->eventHandler_;
  }

  public function process(TProtocol $input, TProtocol $output) {
    $rseqid = 0;
    $fname = null;
    $mtype = 0;

    $input->readMessageBegin($fname, $mtype, $rseqid);
    $methodname = 'process_'.$fname;
    if (!method_exists($this, $methodname)) {
      $handler_ctx = $this->eventHandler_->getHandlerContext($methodname);
      $this->eventHandler_->preRead($handler_ctx, $methodname, array());
      $input->skip(TType::STRUCT);
      $input->readMessageEnd();
      $this->eventHandler_->postRead($handler_ctx, $methodname, array());
      $x = new TApplicationException('Function '.$fname.' not implemented.', TApplicationException::UNKNOWN_METHOD);
      $this->eventHandler_->handlerError($handler_ctx, $methodname, $x);
      $output->writeMessageBegin($fname, TMessageType::EXCEPTION, $rseqid);
      $x->write($output);
      $output->writeMessageEnd();
      $output->getTransport()->flush();
      return;
    }
    $this->$methodname($rseqid, $input, $output);
    return true;
  }

  protected function process_Log($seqid, TProtocol $input, TProtocol $output) {
    $handler_ctx = $this->eventHandler_->getHandlerContext('Log');
    $reply_type = TMessageType::REPLY;

    $this->eventHandler_->preRead($handler_ctx, 'Log', array());

    $bin_accel = ($input instanceof TProtocol::$TBINARYPROTOCOLACCELERATED) && function_exists('thrift_protocol_read_binary_struct');
    $compact_accel = ($input instanceof TProtocol::$TCOMPACTPROTOCOLACCELERATED) && function_exists('thrift_protocol_read_compact_struct') && TCompactProtocolAccelerated::checkVersion(1);

    if ($bin_accel) $args = thrift_protocol_read_binary_struct($input, 'Scribe_Log_args');
    else if ($compact_accel) $args = thrift_protocol_read_compact_struct($input, 'Scribe_Log_args');
    else {
      $args = new Scribe_Log_args();
      $args->read($input);
    }
    $input->readMessageEnd();
    $this->eventHandler_->postRead($handler_ctx, 'Log', $args);
    $result = new Scribe_Log_result();
    try {
      $this->eventHandler_->preExec($handler_ctx, 'Log', $args);
      $result->success = $this->handler_->Log($args->messages);
      $this->eventHandler_->postExec($handler_ctx, 'Log', $result);
    } catch (Exception $ex) {
      $reply_type = TMessageType::EXCEPTION;
      $this->eventHandler_->handlerError($handler_ctx, 'Log', $ex);
      $result = new TApplicationException($ex->getMessage());
    }
    $bin_accel = ($output instanceof TProtocol::$TBINARYPROTOCOLACCELERATED) && function_exists('thrift_protocol_write_binary');
    $compact_accel = ($output instanceof TProtocol::$TCOMPACTPROTOCOLACCELERATED) && function_exists('thrift_protocol_write_compact') && TCompactProtocolAccelerated::checkVersion(1);
    $this->eventHandler_->preWrite($handler_ctx, 'Log', $result);
    if ($bin_accel)
    {
      thrift_protocol_write_binary($output, 'Log', $reply_type, $result, $seqid, $output->isStrictWrite());
    }
    else if ($compact_accel)
    {
      thrift_protocol_write_compact($output, 'Log', $reply_type, $result, $seqid);
    }
    else
    {
      $output->writeMessageBegin("Log", $reply_type, $seqid);
      $result->write($output);
      $output->writeMessageEnd();
      $output->getTransport()->flush();
    }
    $this->eventHandler_->postWrite($handler_ctx, 'Log', $result);
  }
}
// HELPER FUNCTIONS AND STRUCTURES

class Scribe_Log_args implements IThriftStruct {
  static $_TSPEC = array(
    1 => array(
      'var' => 'messages',
      'type' => TType::LST,
      'etype' => TType::STRUCT,
      'elem' => array(
        'type' => TType::STRUCT,
        'class' => 'LogEntry',
        ),
        'format' => 'array',
      ),
    );
  public static $_TFIELDMAP = array(
    'messages' => 1,
  );
  const STRUCTURAL_ID = 552798454262890907;
  public $messages = null;

  public function __construct($vals=null) {
    if (is_array($vals)) {
      if (isset($vals['messages'])) {
        $this->messages = $vals['messages'];
      }
    } else if ($vals) {
      throw new TProtocolException(
        'Scribe_Log_args constructor must be passed array or null'
      );
    }
  }

  public function getName() {
    return 'Scribe_Log_args';
  }

  public static function __set_state($vals) {
    return new Scribe_Log_args($vals);
  }

  public function read(TProtocol $input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      if (!$fid && $fname !== null) {
        if (isset(self::$_TFIELDMAP[$fname])) {
          $fid = self::$_TFIELDMAP[$fname];
          $ftype = self::$_TSPEC[$fid]['type'];
        }
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::LST) {
            $this->messages = array();
            $_size0 = 0;
            $_etype3 = 0;
            $xfer += $input->readListBegin($_etype3, $_size0);
            for ($_i4 = 0; $_size0 === null || $_i4 < $_size0; ++$_i4)
            {
              if ($_size0 === null && !$input->readListHasNext()) {
                break;
              }
              $elem5 = null;
              $elem5 = new LogEntry();
              $xfer += $elem5->read($input);
              $this->messages []= $elem5;
            }
            $xfer += $input->readListEnd();
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write(TProtocol $output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('Scribe_Log_args');
    if ($this->messages !== null) {
      if (!is_array($this->messages) && !(($this->messages instanceof Iterator || $this->messages instanceof IteratorAggregate) && $this->messages instanceof Countable)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('messages', TType::LST, 1);
      {
        $output->writeListBegin(TType::STRUCT, count($this->messages));
        {
          foreach ($this->messages as $iter6)
          {
            $xfer += $iter6->write($output);
          }
        }
        $output->writeListEnd();
      }
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class Scribe_Log_result implements IThriftStruct {
  static $_TSPEC = array(
    0 => array(
      'var' => 'success',
      'type' => TType::I32,
      'enum' => 'ResultCode',
      ),
    );
  public static $_TFIELDMAP = array(
    'success' => 0,
  );
  const STRUCTURAL_ID = 5189168095209991118;
  public $success = null;

  public function __construct($vals=null) {
    if (is_array($vals)) {
      if (isset($vals['success'])) {
        $this->success = $vals['success'];
      }
    } else if ($vals) {
      throw new TProtocolException(
        'Scribe_Log_result constructor must be passed array or null'
      );
    }
  }

  public function getName() {
    return 'Scribe_Log_result';
  }

  public static function __set_state($vals) {
    return new Scribe_Log_result($vals);
  }

  public function read(TProtocol $input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      if (!$fid && $fname !== null) {
        if (isset(self::$_TFIELDMAP[$fname])) {
          $fid = self::$_TFIELDMAP[$fname];
          $ftype = self::$_TSPEC[$fid]['type'];
        }
      }
      switch ($fid)
      {
        case 0:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->success);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write(TProtocol $output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('Scribe_Log_result');
    if ($this->success !== null) {
      $xfer += $output->writeFieldBegin('success', TType::I32, 0);
      $xfer += $output->writeI32($this->success);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

?>
