<?php
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Zipkin;

class zipkinCore_CONSTANTS {
  const CLIENT_SEND = "cs";
  const CLIENT_RECV = "cr";
  const SERVER_SEND = "ss";
  const SERVER_RECV = "sr";
  const WIRE_SEND = "ws";
  const WIRE_RECV = "wr";
  const CLIENT_ADDR = "ca";
  const SERVER_ADDR = "sa";

  public static $__values = array(
    "CLIENT_SEND" => "cs",
    "CLIENT_RECV" => "cr",
    "SERVER_SEND" => "ss",
    "SERVER_RECV" => "sr",
    "WIRE_SEND" => "ws",
    "WIRE_RECV" => "wr",
    "CLIENT_ADDR" => "ca",
    "SERVER_ADDR" => "sa",
  );
}

$GLOBALS['zipkinCore_CONSTANTS'] = zipkinCore_CONSTANTS::$__values;

?>
